apiVersion: v2
name: claude-teams-operator
description: A Kubernetes operator for running Claude Code Agent Teams as distributed pods
type: application
version: 0.7.0
appVersion: "0.7.0"
keywords:
  - claude
  - ai
  - agent
  - kubernetes
  - operator
home: https://github.com/amcheste/claude-teams-operator
sources:
  - https://github.com/amcheste/claude-teams-operator
maintainers:
  - name: Alan Chester
    url: https://github.com/amcheste
